"""State definitions for the LangGraph agent."""

from typing import Annotated, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    """State for the agent graph.

    Attributes:
        messages: The conversation messages with automatic merging.
        file_ids: List of file IDs generated by tools.
    """

    messages: Annotated[list[BaseMessage], add_messages]
    file_ids: list[str]
